require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*.rb'

Rspec/NestedGroups:
  Max: 4
